# services:
#   cassandra1:
#     image: cassandra:latest
#     container_name: cassandra1
#     ports:
#       - "9042:9042"
#     environment:
#       - CASSANDRA_CLUSTER_NAME=TestCluster
#       - CASSANDRA_DC=dc1
#       - CASSANDRA_RACK=rack1
#       - CASSANDRA_SEEDS=cassandra1

#   cassandra2:
#     image: cassandra:latest
#     container_name: cassandra2
#     environment:
#       - CASSANDRA_CLUSTER_NAME=TestCluster
#       - CASSANDRA_DC=dc1
#       - CASSANDRA_RACK=rack2
#       - CASSANDRA_SEEDS=cassandra1

#   cassandra3:
#     image: cassandra:latest
#     container_name: cassandra3
#     environment:
#       - CASSANDRA_CLUSTER_NAME=TestCluster
#       - CASSANDRA_DC=dc1
#       - CASSANDRA_RACK=rack3
#       - CASSANDRA_SEEDS=cassandra1


services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra1
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_SEEDS=cassandra1
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
      - CASSANDRA_SEEDS=cassandra1
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
