services:
  cassandra-seed:
    image: cassandra:4.1
    container_name: cassandra-seed
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data-seed:/var/lib/cassandra

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    networks:
      - cassandra-net
    depends_on:
      - cassandra-seed
    volumes:
      - cassandra-data-node2:/var/lib/cassandra

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    networks:
      - cassandra-net
    depends_on:
      - cassandra-seed
    volumes:
      - cassandra-data-node3:/var/lib/cassandra

networks:
  cassandra-net:
    driver: bridge

volumes:
  cassandra-data-seed:
  cassandra-data-node2:
  cassandra-data-node3: